### ISSUE TITLE
Use of the test suite when publishing WIS metadata

### ISSUE THREAD

**Issue by efucile** [wmo-im/pywcmp#2]
Hello @wmo-im/tt-wismd 
we have a new repository with a test suite for wmo cmp. It was developed by @tomkralidis and it is in use in Canada. I believe that this is an extremely useful tool this is why I asked Tom to move it here from the OGC repository. Can you have a look at it please?

**Comment by josusky** [comment]
I have checked it and proposed a small change in the test 9.1.1 - I believe it was giving a false alarm. I hope I have fixed it right. 
Otherwise, I like the tool.

**Comment by tomkralidis** [comment]
Update: TT-WISMD is collaboratively developing pywcmp in support of WCMP implementation (standard, ATS, KPIs, rubric) and associated codelists.
