### ISSUE TITLE
KPI-1 should total 13

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/pywcmp#28]
KPI-1 is [defined](https://github.com/wmo-im/wcmp/blob/master/kpi/001-wcmp-1.3-part2-compliance.adoc#rules-for-implementation) with a total score of 13 (one foreach ATS requirement).  Current implementation in pywcmp provides a score of 0 or 1 (1 if all 13 ATS requirements are passed).

**Comment by josusky** [comment]
OK, this will improve the average score a bit :-) But we should not forget, in the final rating, that the KPI-1 is "pass or fail". Anything below 13 points is an "FX".
