### ISSUE TITLE
KPI_002, non-printable characters in title incorrectly identified.

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/pywcmp#62]
https://github.com/wmo-im/pywcmp/blob/30259599a44ab1839d36248b89f9d4afc0207d11/pywcmp/kpi.py#L227

Test fails when title contains punctuation or spaces, e.g.

```python
title = "My Great Dataset Title"
title.isalnum()
```

returns False

Suggest using isascii().

**Comment by tomkralidis** [comment]
cc @josusky 

PR in #63.  I've also dropped CI testing for Python 3.6 (it's time, and `isascii` was introduced in 3.7).
