### ISSUE TITLE
Tests for global data exchange

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/pywcmp#64]
Should test 9_2_1 or 9_3_1 be run if the data are not marked for global exchange?

https://github.com/wmo-im/pywcmp/blob/30259599a44ab1839d36248b89f9d4afc0207d11/pywcmp/ats.py#L110-L115

If the data are not marked for global exchange then the rules for the gmd:fileIdentifier are different / more relaxed. Page 50, section 8.1 of the manual on WIS (https://library.wmo.int/doc_num.php?explnum_id=11077), my emphasis.

> The WMO Core Metadata Profile recommends the use of a URI structure for gmd:fileIdentifier 
> attributes. The URI should be structured as follows:
> • Fixed string “urn:x-wmo:md:”;
> • **Citation authority based on the Internet domain name of the data-provider organization, 
> e.g. “int.wmo.wis”, “gov.noaa”, “edu.ucar.ncar”, “cn.gov.cma” or “uk.gov.metoffice”;**
> • Double separator colons: “::”;
> • Unique identifier:
> – For metadata records describing GTS products in bulletins or named according to 
> the WMO file-naming convention P-flag = “T” or P-flag= “A”, the unique identifier is 
> “«TTAAii»«CCCC»”;
> – For metadata records describing products named according to the WMO file-naming 
> convention P-flag = “W”, the unique identifier should be a truncated version of the 
> WMO product identifier field of the associated data-files, excluding the date-stamp 
> and any other varying elements as necessary;

**Comment by tomkralidis** [comment]
@david-i-berry good point. Would this also be the case for req 9.3.2?

**Comment by david-i-berry** [comment]
Reading the test it looks that way.
