### ISSUE TITLE
add wcmp2 validation

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/pywcmp#71]
Add the ability for pywcmp to validate a WCMP2 document.  Example:

```bash
pywcmp ats validate --file /path/to/file.json
```

Note that we'll need to have a generic detection mechanism across pywcmp that will route the workflow to WCMP1 or WCMP2 accordingly (e.g. if JSON, then WCMP2, else WCMP1).

Note that setup will need to be updated to download the WCMP2 schemas.

**Comment by josusky** [comment]
I guess this one can be closed, you have already added wcmp2 validation. For the outstanding issues we can create more specific issues.
