### ISSUE TITLE
Add validation of KPI 13

### ISSUE THREAD

**Issue by josusky** [wmo-im/pywcmp#74]
That was the last KPI that we described (in July 2021) and somehow we forgot to implement it in the `pywcmp` tool. (see https://github.com/wmo-im/wcmp/issues/120)

**Comment by josusky** [comment]
* I am sure we can test the first (fixed) part "urn:x-wmo:md:", that is easy :-)
* The second part is more tricky but something can be done:
** we can test the structure of the identifier and the first level (e.g. "edu", "cn") off-line
** if we want (and have enough time) we can resolve the whole thing to see if it is a valid domain name, for example, "ncar.ucar.edu" resolves to "23.185.0.1", in other words, it is a valid DNS entry.
When it concerns the uniqueness of the identifier, there I suggest not to even try. After all, the KPI talks about *structure*, that is _syntax_ not so much about the _semantics_.

**Comment by amilan17** [comment]
Don't add for 1.3 KPIs
