### ISSUE TITLE
Move KPI-12 to KPI-5 to avoid gap in the KPI numbering

### ISSUE THREAD

**Issue by josusky** [wmo-im/pywcmp#79]
Now, when the KPI-5 does not exist any more (it has been merged with KPI-9), the numbering has a gap - that is a bit confusing. During the [meeting](https://github.com/wmo-im/tt-wismd/wiki/Meeting-2022-07-27), it has been agreed to fix it by renumbering KPI-12 to KPI-5.

**Comment by amilan17** [comment]
@josusky -- This branch has all of the latest changes as discussed in the last meeting: https://github.com/wmo-im/wcmp/tree/issue128new/kpi
