### ISSUE TITLE
Update KPI-7 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/pywcmp#84]
Testing for gmx:Anchor is too restrictive and during the last cycle of KPI testing all records received a 0 on KPI-7.  

I think we should simplify the XPath for tests 7.1 and 7.2, but then add a 3rd test for gmx:Anchor and change the total score to 3. This is consistent with other KPIs like keywords and data policy. @tomkralidis --OK? 

Change  //gmd:identificationInfo/gmd:MD\_DataIdentification/gmd:graphicOverview/gmd:MD\_BrowseGraphic/gmd:fileName/gmx:Anchor

//gmd:identificationInfo/gmd:MD\_DataIdentification/gmd:graphicOverview/gmd:MD\_BrowseGraphic/gmd:fileName

See previous discussions in issue wmo-im/wcmp#124.

**Comment by josusky** [comment]
The total score was `3 * N`, where "N" was number of "graphicOverview" elements. I will fix URL retrieval (to allow use of "gco:CharacterString") and fix the evaluation to take just the first "graphicOverview" into account to ensure that the total score is not more than 3 - that is consistent with the changes related to the title element.
BTW, the KPI 7 in `pywcmp` always had three test (as described in https://github.com/wmo-im/wcmp/blob/1.3/kpi/007-graphic-overview-for-non-bulletins-metadata-records.adoc). Current version of the KPI 7 contains only two tests:
https://github.com/wmo-im/wcmp/blob/master/kpi/007-graphic-overview.adoc 
Hm ...

**Comment by amilan17** [comment]
@josusky -- This is not fixed yet, because it looks the the Xpath is still restricted in a different location.  
https://github.com/wmo-im/pywcmp/blob/b3d0a9a7ca73237a93a52c16123f2e721d21e2f2/pywcmp/kpi.py#L436

**Comment by amilan17** [comment]
sorry, rescinding last comment. wrong KPI.

**Comment by amilan17** [comment]
it's fixed.
