### ISSUE TITLE
KPI-5 returns score 0 for everything

### ISSUE THREAD

**Issue by amilan17** [wmo-im/pywcmp#86]
I recommend that we change the pywcmp for KPI-5 to only test when DOI's exist. 
This will be consistent with the approach we are taking with KPI-7 (graphic overview). Given that this is a relatively recent practice in metadata management, giving a score of 0 is quite harsh. What do you think? 

![image](https://user-images.githubusercontent.com/5168866/190381464-cc1f3503-a7e3-46b4-9185-9dc05c5b8003.png)

**Comment by josusky** [comment]
Hm, you mean to set the "total" for the KPI-5 to "0" if there is no '//gmd:identificationInfo//gmd:citation//gmd:identifier//gmd:code/gmx:Anchor' element?
BTW, this KPI (it was initially KPI-12) may yield a total score that is a multiple of 3 (i.e. it evaluates all elements that match the aforementioned XPath).
Eeek, it sets the total score to 6 if it finds one matching element so the best you can get is 3 of 6. That is really harsh ;-)
I will fix that one, but I am not sure about the rest.

**Comment by josusky** [comment]
OK, I have changed the KPI-5 check in the pywcmp to check only the first matching element and to set the total score to 0 if there is none.

**Comment by amilan17** [comment]
thanks.
